### ISSUE TITLE
pulsar-heart beat broker health check returns incorrect information

### ISSUE THREAD

**Issue by yabinmeng** [datastax/pulsar-heartbeat#19]
# Description
I have a single 1-node Pulsar cluster (not running in standalone mode) and I'd like to test out using a standalone Pulsar-heartbeat to monitor the health of the cluster.

I tested the end-to-end latency, broker health, and rest API health. Among these 3 tests, it looks like broker health returns the wrong information
`2021/11/30 17:07:24  info  broker received counter 1 app=broker health monitor
2021/11/30 17:07:24  info cluster clusterA has 1 failed brokers out of total 1 brokers app=broker health monitor
2021/11/30 17:07:24 error cluster clusterA-brokers has 1 unhealthy brokers, error message: failed to get message on topic persistent://pulsar/clusterA/ip-10-101-33-190.srv101.dsinternal.org:8080/healthcheck;`

The broker is up and running all the time. I'm able to run pulsar commands without issue and also when I run the health check rest API (https://pulsar.apache.org/admin-rest-api/#operation/healthcheck), it returns "ok".

## Tested Pulsar Version 
OSS Pulsar 2.7.3 and 2.8.1

## runtime YAML file
```
name: my-pulsar-heartbeat-demo
token:
trustStore:
pagerDutyConfig:
  integrationKey:
slackConfig:
  alertUrl:
prometheusConfig:
  port: ":8089"
  exposeMetrics: true
k8sConfig:
  enabled: false
pulsarTopicConfig:
  - latencyBudgetMs: 2400
    numberOfPartitions: 0
    clusterName: clusterA
    pulsarUrl: pulsar://<node_ip>:6650
    adminUrl: http://<node_ip>:8080
    topicName: persistent://pulic/default/phb-demo-0
    payloadSizes: ["15B"]
    intervalSeconds: 60
    numberOfMessages: 1
    alertPolicy:
      Ceiling: 5
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 10


pulsarAdminRestConfig:
  intervalSeconds: 60 
  clusters:
    - name: {cluster name}
      url: "http://<node_ip>:8080" 
      alertPolicy:
        Ceiling: 5
        MovingWindowSeconds: 600
        CeilingInMovingWindow: 8
```
